version: "2"
#use: golangci-lint run --fix
run:
  modules-download-mode: readonly

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(order-service)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0