DROP INDEX IF EXISTS idx_items_order_uid;
DROP INDEX IF EXISTS idx_orders_customer_id;
DROP INDEX IF EXISTS idx_orders_date_created;

DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS orders CASCADE;